-- Longhorn Preflight Schema
-- Run this in Supabase Dashboard: Database → SQL Editor

-- Create messages table
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    content TEXT NOT NULL CHECK (length(content) <= 1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist (for clean setup)
DROP POLICY IF EXISTS "select_any_authenticated" ON public.messages;
DROP POLICY IF EXISTS "insert_any_authenticated" ON public.messages;

-- Create policy for SELECT: any authenticated user can read all messages
CREATE POLICY "select_any_authenticated" 
ON public.messages 
FOR SELECT 
USING (auth.role() = 'authenticated');

-- Create policy for INSERT: any authenticated user can insert messages
CREATE POLICY "insert_any_authenticated" 
ON public.messages 
FOR INSERT 
WITH CHECK (auth.role() = 'authenticated');

-- Grant necessary permissions
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT ALL ON public.messages TO authenticated;
GRANT USAGE ON SEQUENCE public.messages_id_seq TO authenticated;